name: wasm-r3 tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.x'
    - run: npm install && npx playwright install
    - name: Download Binaryen
      run: |
        wget https://github.com/WebAssembly/binaryen/releases/download/version_117/binaryen-version_117-x86_64-linux.tar.gz
        tar xvf binaryen-version_117-x86_64-linux.tar.gz
        sudo mv binaryen-version_117/bin/* /usr/local/bin/
    - run: npm run build
    - run: npm test core
    - run: npm test proxy
